export const genericBooking = {
  "provider": {
    "id": 6,
    "name": "Leandro Abreu",
    "qty": 1,
    "email": "leandro@weef.com.br",
    "description": "",
    "phone": "",
    "picture": null,
    "picture_preview": null,
    "color": null,
    "is_active": true,
    "is_visible": true,
    "services": [
      "2",
      "3"
    ]
  },
  "service": {
    "id": 3,
    "name": "Mentoria Individual",
    "description": null,
    "price": null,
    "currency": null,
    "tax_id": null,
    "tax": null,
    "duration": 60,
    "buffer_time_after": 0,
    "recurring_settings": null,
    "picture": null,
    "picture_preview": null,
    "memberships": [],
    "providers": [
      2,
      4,
      3,
      5,
      6,
      7,
      8
    ],
    "is_active": true,
    "is_visible": true,
    "duration_type": null,
    "limit_booking": null,
    "min_group_booking": null
  },
  "client": {
    "can_be_edited": true,
    "is_deleted": null,
    "id": 25,
    "name": "Thiago França",
    "email": "thiago@minify.com.br",
    "phone": "+55 11 999999999",
    "address1": null,
    "address2": null,
    "city": null,
    "zip": null,
    "country_id": null,
    "state_id": null,
    "full_address": ""
  },
  "status": "confirmed",
  "membership_id": null,
  "invoice_id": null,
  "invoice_status": null,
  "invoice_payment_received": false,
  "invoice_number": null,
  "invoice_datetime": null,
  "invoice_payment_processor": null,
  "ticket_code": null,
  "ticket_validation_datetime": null,
  "ticket_is_used": null,
  "testing_status": null,
  "user_status_id": null,
  "category": null,
  "location": null,
  "can_be_edited": true,
  "can_be_canceled": true,
  "booking_details": {
    "social_network": "generic",
    "main_topic": "generic",
    "specific_questions": "generic"
  }
}